### ISSUE TITLE
Support libftdi 1.5

### ISSUE THREAD

**Issue by h5rdly** [codedstructure/pylibftdi#1]
Hi,

First of all, cheers for making this Python wrapper!

I wanted to ask - would you be adding support to the recent version of libftdi?

Thanks,
Eli

**Comment by codedstructure** [comment]
It's intended to work with recent libftdi versions - what operating system are you using?

On a MacOS BigSur system with libftdi installed used homebrew, pylibftdi basically works fine for me with following details:

```
(venv) Bens-MacBook-Air:pylibftdi ben$ python3 -m pylibftdi.examples.list_devices
FTDI:UMFT230XB:FT[xxxxxx]
(venv) Bens-MacBook-Air:pylibftdi ben$ python3 -m pylibftdi.examples.info
pylibftdi version     : 0.19.0
libftdi version       : libftdi_version(major=1, minor=5, micro=0, version_str=b'1.5', snapshot_str=b'unknown')
libftdi library name  : /usr/local/lib/libftdi1.dylib
libusb version        : libusb_version(major=1, minor=0, micro=24, nano=11584, rc=b'', describe=b'http://libusb.info')
libusb library name   : /usr/local/lib/libusb-1.0.dylib
Python version        : 3.9.7
OS platform           : macOS-11.6.1-x86_64-i386-64bit
```

If there is anything specific not working, please let me know with output from the 'pylibftdi.examples.info' example above, but bear in mind I can't test every combination of OS & device.

**Comment by codedstructure** [comment]
Closing - this works fine with libftdi 1.5 as far as I can tell.
