### ISSUE TITLE
FYI the "Edit on GitHub" button in read the docs is broken

### ISSUE THREAD

**Issue by rickwierenga** [codedstructure/pylibftdi#3]
First off, thanks for the lib!

The docs links to the master branch, whereas the repo uses main. I think this is handled by some hidden read the docs config panel, as I could not find the https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-github_url in the conf.py.

**Comment by codedstructure** [comment]
Thanks for letting me know - much appreciated!

I've fixed this (link works and v0.20.0 docs now exist) by following the instructions here: https://github.com/readthedocs/readthedocs.org/issues/7907#issuecomment-1129750962
