### ISSUE TITLE
Note: Must use python <= 3.11. 

### ISSUE THREAD

**Issue by phelps-matthew** [codedstructure/pylibftdi#7]
I spent a lot of time trying to figure out why I was getting an error related to not being able to access the shared libftdi libraries. Turns out the latest python version is incompatible. 

Posting this here in the even this may save someone else much troubleshooting.

To be fair, I did later find 3.11 to be the highest listed in the pyproject.toml.

**Comment by GeorgeIoak** [comment]
Thanks, you helped me stop banging my head for an head!
